export { InventoryDashboardPage } from './InventoryDashboardPage'
export { ProductsPage } from './ProductsPage'
export { ProductDetailPage } from './ProductDetailPage'
export { StockMovementsPage } from './StockMovementsPage'
export { InventoryCategoriesPage } from './InventoryCategoriesPage'
export { WarehousesPage } from './WarehousesPage'
